document.write("Versión: ");
document.write(infoNavegador.version);
document.write("<br>");
document.write("Plataforma: ");
document.write(infoNavegador.plataforma);
document.write("<br>");
document.write("Vendedor: ");
document.write(infoNavegador.vendedor);
document.write("<br>");
document.write("Agente: ");
document.write(infoNavegador.agente);
document.write("<br>");
document.write("Java activo: ");
document.write(infoNavegador.javaActivo);